name: First Workflow

# Manual trigger
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello from Actions!"
      - name: Print goodbye
        run: echo "goodbye"
